name: commit-stage-monolith-java

on:
  push:
    branches: [ "main" ]
    paths:
        - 'monolith-java/**'
        - '.github/workflows/commit-stage-monolith-java.yml'
  pull_request:
    branches: [ "main" ]
    paths:
        - 'monolith-java/**'
        - '.github/workflows/commit-stage-monolith-java.yml'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: monolith-java

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag monolith-java:${{ github.sha }}

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker image
        run: docker tag monolith-java:${{ github.sha }} ghcr.io/${{ github.repository }}/monolith-java:latest

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/monolith-java:latest