name: local-acceptance-stage-java

on:
  push:
    branches: [ "main" ]
    paths:
        - 'system-test-java/**'
        - '.github/workflows/local-acceptance-stage-java.yml'
  pull_request:
    branches: [ "main" ]
    paths:
        - 'system-test-java/**'
        - '.github/workflows/local-acceptance-stage-java.yml'
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: system-test-java

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0

    - name: Make Gradle Wrapper executable
      run: chmod +x ./gradlew

    - name: Docker Compose Up
      run: docker compose up -d

    - name: Run Smoke Tests
      run: ./gradlew test --tests com.optivem.atddaccelerator.template.systemtest.smoketest.*